require 'options'
require 'colors'
require 'keymaps'
require 'plugins'

require 'plugin.gruvbox'
require 'plugin.nvim-tree'
require 'plugin.scrollbar'
require 'plugin.lualine'
require 'plugin.bufferline'
require 'plugin.toggleterm'
require 'plugin.cmp'
require 'plugin.lsp.lspconfig'
require 'plugin.lsp.lspsaga'
